require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'RNWorkInProgress' do
  config = use_native_modules!
  ruby = use_frameworks! # Add this if you are targeting iOS 8+ or using Swift
pod 'CocoaAsyncSocket'

  use_react_native!(:path => config["reactNativePath"])

  target 'RNWorkInProgressTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  # use_flipper!
  # post_install do |installer|
  #   flipper_post_install(installer)
  # end
end

target 'RNWorkInProgress-tvOS' do
  # Pods for RNWorkInProgress-tvOS

  target 'RNWorkInProgress-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
